import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import type { CompilerContext, CompilerInput, CompilerOutput } from "../types.js";

function renderTemplate(template: string, ctx: CompilerContext): string {
  return template.replaceAll(/\{\{\s*([^}]+)\s*\}\}/g, (_match, expr) => {
    const rawValue = resolveTemplatePath(expr.trim(), ctx);
    return rawValue == null ? "" : String(rawValue);
  });
}

function resolveTemplatePath(expression: string, ctx: CompilerContext): unknown {
  const segments = expression.split(".");
  let current: unknown = ctx;

  for (const segment of segments) {
    if (current == null || typeof current !== "object") {
      return undefined;
    }

    current = (current as Record<string, unknown>)[segment];
  }

  return current;
}

function parseNameBrokerage(value: string | undefined, fallbackName: string | undefined): {
  firstName: string;
  brokerage: string;
} {
  if (!value) {
    return {
      firstName: fallbackName ?? "Agent",
      brokerage: ""
    };
  }

  const [namePart, ...brokerageParts] = value.split(",");
  const firstName = namePart?.trim().split(/\s+/)[0] ?? fallbackName ?? "Agent";

  return {
    firstName,
    brokerage: brokerageParts.join(",").trim()
  };
}

function parseTime(timeLabel: string | undefined): { hour: number; minute: number; label: string } {
  const fallback = { hour: 7, minute: 0, label: "7:00 AM" };

  if (!timeLabel) {
    return fallback;
  }

  const match = timeLabel.match(/^(\d{1,2}):(\d{2})\s*(AM|PM)$/i);
  if (!match) {
    return { ...fallback, label: timeLabel };
  }

  let hour = Number(match[1]);
  const minute = Number(match[2]);
  const period = (match[3] ?? "AM").toUpperCase();

  if (period === "PM" && hour !== 12) {
    hour += 12;
  }

  if (period === "AM" && hour === 12) {
    hour = 0;
  }

  return { hour, minute, label: timeLabel };
}

function buildContext(input: CompilerInput): CompilerContext {
  const { answers, bundle, user } = input;
  const nameBrokerage = parseNameBrokerage(answers.name_brokerage, user.name);

  return {
    role: bundle,
    onboarding: answers,
    user,
    firstName: nameBrokerage.firstName,
    brokerage: nameBrokerage.brokerage,
    markets: (answers.markets ?? "")
      .split(",")
      .map((market) => market.trim())
      .filter(Boolean),
    digestTime: parseTime(answers.digest_time),
    tone: answers.tone ?? "Professional and direct"
  };
}

function formatTrigger(type: string, value: string, ctx: CompilerContext): string {
  if (type === "cron") {
    return `${resolveCron(value, ctx)} (${ctx.digestTime.label})`;
  }

  if (type === "intent") {
    return `intent regex: ${value}`;
  }

  return `event: ${value}`;
}

function resolveCron(template: string, ctx: CompilerContext): string {
  if (template === "0 7 * * *") {
    return `${ctx.digestTime.minute} ${ctx.digestTime.hour} * * *`;
  }

  return template;
}

function compileAgentsMd(ctx: CompilerContext, compiledAt: string): string {
  const lines: string[] = [
    `# ClawSuit — ${ctx.role.name}`,
    `<!-- Generated by ClawSuit compiler v${ctx.role.version} -->`,
    `<!-- Role: ${ctx.role.slug} | Compiled: ${compiledAt} -->`,
    "",
    "## Active role",
    `**${ctx.role.name}** - ${ctx.role.description}`,
    "",
    "## Skills",
    ...ctx.role.skills.map((skill) => `- ${skill}`),
    "",
    "## Workflows"
  ];

  for (const workflow of ctx.role.workflows) {
    lines.push("");
    lines.push(`### ${workflow.name} (\`${workflow.id}\`)`);
    lines.push(`- Trigger: ${formatTrigger(workflow.trigger.type, workflow.trigger.value, ctx)}`);
    lines.push(`- Description: ${workflow.description}`);
    lines.push("- Steps:");

    for (const [index, step] of workflow.steps.entries()) {
      lines.push(`  ${index + 1}. ${step.id} -> \`${step.skill}\``);
    }
  }

  return lines.join("\n");
}

function compileSoulMd(ctx: CompilerContext): string {
  return [
    "# Soul",
    "",
    "## Identity",
    renderTemplate(ctx.role.soul.persona, ctx),
    "",
    "## Tone",
    ctx.tone,
    "",
    "## Boundaries",
    ...ctx.role.soul.boundaries.map((boundary) => `- ${boundary}`),
    "",
    "## Active role context",
    `You are currently acting as ${ctx.role.name}.`,
    `Keep replies aligned with ${ctx.firstName}${ctx.brokerage ? ` at ${ctx.brokerage}` : ""}.`
  ].join("\n");
}

function compileMemoryMd(ctx: CompilerContext): string {
  return [
    "# Memory",
    "",
    "## User profile",
    `- Name: ${ctx.firstName}`,
    ctx.brokerage ? `- Brokerage: ${ctx.brokerage}` : "",
    `- Role: ${ctx.role.name}`,
    `- Markets: ${ctx.markets.join(", ") || "Unspecified"}`,
    ctx.onboarding.email ? `- Email: ${ctx.onboarding.email}` : "",
    `- Preferred tone: ${ctx.tone}`,
    `- Preferred channel: ${ctx.role.channels.primary}`,
    "",
    "## Preferences",
    `- Digest time: ${ctx.digestTime.label}`,
    "- Locale: en-CA",
    "- Currency: CAD",
    "",
    "## Data connections",
    ...ctx.role.dataConnections.map((connection) =>
      `- ${connection.service}: ${connection.required ? "required" : "optional"}`
    )
  ].filter(Boolean).join("\n");
}

function compileUserMd(ctx: CompilerContext): string {
  const cronSchedules = ctx.role.workflows
    .filter((workflow) => workflow.trigger.type === "cron")
    .map((workflow) => `${resolveCron(workflow.trigger.value, ctx)} run-workflow ${workflow.id}`);

  return [
    "# User configuration",
    "",
    "## Scheduled workflows",
    "```text",
    ...cronSchedules,
    "```",
    "",
    "## Messenger channel",
    `primary: ${ctx.role.channels.primary}`,
    ctx.role.channels.fallback ? `fallback: ${ctx.role.channels.fallback}` : "",
    "",
    "## LLM preferences",
    "default_model: claude-haiku-4-5-20251001",
    "complex_model: claude-sonnet-4-6",
    "max_tokens_per_workflow: 4000"
  ].filter(Boolean).join("\n");
}

export async function compileRole(input: CompilerInput): Promise<CompilerOutput> {
  const compiledAt = new Date();
  const context = buildContext(input);
  const compiledAtIso = compiledAt.toISOString();

  const files: CompilerOutput["files"] = {
    "AGENTS.md": compileAgentsMd(context, compiledAtIso),
    "SOUL.md": compileSoulMd(context),
    "MEMORY.md": compileMemoryMd(context),
    "USER.md": compileUserMd(context)
  };

  if (input.outputDir) {
    await mkdir(input.outputDir, { recursive: true });

    await Promise.all(
      Object.entries(files).map(([filename, content]) =>
        writeFile(path.join(input.outputDir as string, filename), content, "utf8")
      )
    );
  }

  return {
    files,
    compiledAt
  };
}
